### ISSUE TITLE
Android - Background APP - Notification Callback

### ISSUE THREAD

**Issue by murliatdure** [one-signal/OneSignal-Cordova-SDK#12]
Here are the observations - 

1. When app is in background (via back button) - notification callback desn't work/even no updates on notification tray

2. When app is in background (via home button) - notification callback doesn't support, rather it brings notifications on notification tray

Can we have some provision for consistent behavior.

Can we have some idea to sync all requests without opening the item from tray, as after click this gets I can write some callback, I would like to get all incoming envelopes into localstorage, so that whether user opens/dismiss the item the logic should be consistent.

**Comment by jkasten2** [comment]
Hello,

1. I have tested closing a Cordova app with the back button and notifications are shown in the notification area without issue. I have verify this works correctly with builds from both Cordova 5.2 and PhoneGap Build (PGB) running on both Android 5.0.2 and Android 4.3.

2. This is expected behavior, if the app is in the background or is not running at all notifications are sent to the notification area. The notification opened callback is only fired when a notification is tapped on or one is received when the user is using your app.

Can you please provide an example project to reproduce your 1st issue? Include steps to reproduce the issue as well as the Android version you're seeing this on.

Thanks.

**Comment by murliatdure** [comment]
PGB version-3.7
Android Version : 5.0 (L)

**Comment by jkasten2** [comment]
@murliatdure Could you provide an example project with steps to reproduce your 1st issue? You can create a new project on the github and attach it here or send a zip to support@onesignal.com.

Thanks.
