### ISSUE TITLE
Local Notification + OneSignal - PGB Fails

### ISSUE THREAD

**Issue by murliatdure** [one-signal/OneSignal-Cordova-SDK#18]
Android SDK API: 22
Cordova CLI: 5.3.3

OneSignal plugins:
<gap:plugin name="onesignal-cordova-plugin-pgb-compat" source="npm" />
<gap:plugin name="cordova-plugin-googleplayservices" source="npm" />
<gap:plugin name="cordova-plugin-android-support-v4" source="npm" />

Local Notification plugins:
<gap:plugin name="de.appplant.cordova.plugin.local-notification" />
![1](https://cloud.githubusercontent.com/assets/7137859/10483644/0dc4202a-729e-11e5-8e9d-3e9dd72a9d61.png)

And updating the Local Notification plugin from NPM sources results -
<gap:plugin name="cordova-plugin-local-notifications" source="npm" />

gives output as - 
![local-notification](https://cloud.githubusercontent.com/assets/7137859/10483030/83016676-729a-11e5-9308-6c60744acefb.PNG)

Looking for the support.

**Comment by jkasten2** [comment]
Can you try [`cordova-plugin-local-notifications-mm`](https://www.npmjs.com/package/cordova-plugin-local-notifications-mm) instead of [`cordova-plugin-local-notifications`](https://www.npmjs.com/package/cordova-plugin-local-notifications)?
```xml
<gap:plugin name="cordova-plugin-local-notifications-mm" source="npm" />
```
The above worked for me to build the project with both plugins included however you will need to test to make sure local notification and OneSignal still work for you.

Also phonegap `cli-5.3.3` is not available on PGB yet. The latest you can use is `cli-5.2.0`.

I am not sure which one is 'official' as I don't see any npmjs.com entries pointing to [katzer/cordova-plugin-local-notifications](https://github.com/katzer/cordova-plugin-local-notifications). @katzer does your main repo live on npm currently?

Thanks.

**Comment by jkasten2** [comment]
I believe cordova-plugin-local-notifications-mm should work for you. Let us know if it does not.

Thanks.
