### ISSUE TITLE
Update badge icon only

### ISSUE THREAD

**Issue by vespino** [one-signal/OneSignal-Cordova-SDK#32]
My client asked me if it's possible to update the badge icon of an app without the regular pushnotification action (message at the top of the screen + screen on). Is this possible? And does Android support badge icons?

**Comment by jkasten2** [comment]
Hello,

It is possible to update just the badge number on iOS without sending a notification. To do so please enable content_available on the notification, set both ios_badgeType and ios_badgeCount, and lastly omit sending contents (message body) with the notification to keep a message from displaying. This can also be done from our dashboard in addition to the REST API.

We currently do not have support for Android badge numbers since this isn't built into the official Android launcher. You can follow issue #29 for updates on this.

Thanks.

**Comment by vespino** [comment]
What exactly do you mean by "and lastly omit sending contents (message body) with the notification to keep a message from displaying"? I now send the following information to the REST API:

contents => my message
isIos => true
ios_badgeType => Increase
ios_badgeCount => 1

Can you tell me what to add or change?

**Comment by jkasten2** [comment]
By "without the regular pushnotification action (message at the top of the screen + screen on)" I was thinking you wanted to omit displaying anything on the device other than the badge number. Including the lock screen and the Notification Center. Is this not the case?

If you just need to update the badge number you can send the following:
```
isIos => true
ios_badgeType => Increase
ios_badgeCount => 1
content_available => true
```

Thanks.

**Comment by vespino** [comment]
Thanks, yes that is what I'm looking for, only updating the badge number and doing nothing else. I will try this.

**Comment by jkasten2** [comment]
Closing issue, feel free to open this issue if the silent badge updating isn't working.

**Comment by Aarbel** [comment]
![image](https://user-images.githubusercontent.com/25119847/63050569-b973cc80-bedb-11e9-906f-da2818f9b5dc.png)

Just a screenshot for OneSignal setting to help others. Works great
