### ISSUE TITLE
Notifications not received when app is closed

### ISSUE THREAD

**Issue by imadarchid** [one-signal/OneSignal-Cordova-SDK#9]
I would like to send push notifications to my Android app even if the user didn't open the app. I only can receive notifications if app is opened, or running in background. If I kill it using the Task Manager, I can't receive any messages.

Thanks

**Comment by jkasten2** [comment]
Hello,

If the system closes your app to free RAM or the user closes the app from the Recent Apps list your app will still display notifications to the notification area. If they "Force Stop" the app from Settings>Apps or with a 3rd party task manager that uses the same method then notifications will not be received until they open the app again or reboot the device. This is because GCM no longer wakes up the app's GCM receiver.

Thanks.

**Comment by imadarchid** [comment]
Thanks for the answer @jkasten2 ! But the problem is, when I boot up my phone I don't receive any notification until I open the app and close it. 
I would like to be able to receive notifications the moment I boot up my phone.

**Comment by jkasten2** [comment]
I did some testing on an Android 5.0.2 and a 4.3 device and it seems rebooting does not reset the "Force stop" state of the app. Only reopening the app once allows it to receive notifications again. If the app was closed normally and you reboot the device notifications are received after it boots up however.

Most users would never go into Settings>Apps then press the "Force Stop" button. Which Task Manager are you using to reproduce the issue? I have tried a few in the past like "Advanced Task Killer" and it does not affect push notifications.

Thanks.

**Comment by uzumakinaruto123** [comment]
@jkasten2  sometimes notifications stop showing up like they are queued. i wonder is it because of task killers. but, on the other hand , how can app reveive a notification that is sent from the dashboards test message ? i tried killing the app and sending test notification from dashboard, notification is received successfully.

**Comment by Mariamjamal32** [comment]
Hey, I am really new in working with notifications. I would like to know if there is a way that the notifications I send got received by intended parties but not to the sending device/sender?

**Comment by dsfgsdfgf** [comment]
> When your app is placed into the "Stopped State" all BroadcastReceivers in your app will stop receiving intents. This includes GCM intents that fire when a notification message is received from Google. This is a known and expected behavior for Android 3.1 and newer.


@jkasten2 I've tried implementing a background service and tried to make a persistent broadcastreceiver with the service... But still as you mention, when app is closed/swiped away/onDestroy() triggered, it is not able to process intents from within onNotificationReceived() to any remote process ? Could you advise of any workarounds to get package manager to launch an activity from within this callbac ? Thanks.

**Comment by jkasten2** [comment]
@dsfgsdfgf I am not sure I understand you question. Are you seeing a notification on your device when the app is swiped away? If not please see the `The app is Force Stopped` section in our troubleshooting guide below. Some manufactures customize Android for Force Stop / Kill apps.
https://documentation.onesignal.com/docs/notifications-show-successful-but-are-not-being-shown

**Comment by NurGuz** [comment]
Hi,

same problem here. Don't run with this  GCM push notification works after app Force Stop?
BroadcastReceiver not receiving BOOT_COMPLETED
